### ISSUE TITLE
DB close connection

### ISSUE THREAD

**Issue by nirLebo** [manjeshpv/node-express-passport-mysql#6]
Hi,

Thank you for your project it help me a lot !
I dont know if you still maintain the project but i use it today and i got this error:

> Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\wamp\www\Test_projects\fb\node-express-passport-mysql-ma
ster\node_modules\mysql\lib\protocol\Protocol.js:109:13)
    at Socket.<anonymous> (C:\wamp\www\Test_projects\fb\node-express-passport-my
sql-master\node_modules\mysql\lib\Connection.js:102:28)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)

I solved it by closing the connection after every db request.

**Comment by vikasjson** [comment]
Please create a pull request
