### ISSUE TITLE
database errors

### ISSUE THREAD

**Issue by Mattscoo** [manjeshpv/node-express-passport-mysql#9]
Apologies for the newbie question: but running "node scripts/create_database.js" during the setup process returns the error:

```
Success: Database Created!
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

```
And if I try running "node server.js" (even though the previous step didn't work), I get:

```
The magic happens on port 8080
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14) 
```

I'm confused because, I don't even understand which file the error is occurring in. Searching the error online did not yield any fruitful results for me. Are there a specific couple of lines of code I have to change, and if so in which file (and how)? Thank you.

**Comment by manjeshpv** [comment]
See this file

https://github.com/manjeshpv/node-express-passport-mysql/blob/master/config/database.js
